import asyncio
import logging
import warnings
from pathlib import Path

import click
import uvicorn
from eth_typing import ChecksumAddress
from sw_utils import EventScanner, InterruptHandler

import src
import src.validators.api.endpoints  # noqa
from src.api import app as api_app
from src.common.consensus import get_chain_finalized_head
from src.common.execution import WalletTask, get_oracles
from src.common.metrics import MetricsTask, metrics_server
from src.common.startup_check import startup_checks
from src.common.utils import JsonFormatter, get_build_version, log_verbose
from src.common.validators import validate_eth_address
from src.common.vault_config import VaultConfig
from src.config.settings import (
    AVAILABLE_NETWORKS,
    DEFAULT_API_HOST,
    DEFAULT_API_PORT,
    DEFAULT_MAX_FEE_PER_GAS_GWEI,
    DEFAULT_METRICS_HOST,
    DEFAULT_METRICS_PORT,
    LOG_DATE_FORMAT,
    LOG_FORMATS,
    LOG_JSON,
    LOG_PLAIN,
    settings,
)
from src.exits.tasks import ExitSignatureTask
from src.harvest.tasks import HarvestTask
from src.validators.database import NetworkValidatorCrud
from src.validators.execution import NetworkValidatorsProcessor
from src.validators.keystores.load import load_keystore
from src.validators.tasks import ValidatorsTask, load_genesis_validators
from src.validators.typings import ValidatorsRegistrationMode
from src.validators.utils import load_deposit_data

logger = logging.getLogger(__name__)


@click.option(
    '--data-dir',
    default=str(Path.home() / '.stakewise'),
    envvar='DATA_DIR',
    help='Path where the vault data will be placed. Default is ~/.stakewise.',
    type=click.Path(exists=True, file_okay=False, dir_okay=True),
)
@click.option(
    '--database-dir',
    type=click.Path(exists=True, file_okay=False, dir_okay=True),
    envvar='DATABASE_DIR',
    help='The directory where the database will be created or read from. '
    'Default is ~/.stakewise/<vault>.',
)
@click.option(
    '--max-fee-per-gas-gwei',
    type=int,
    envvar='MAX_FEE_PER_GAS_GWEI',
    help=f'Maximum fee per gas limit for transactions. '
    f'Default is {DEFAULT_MAX_FEE_PER_GAS_GWEI} Gwei.',
    default=DEFAULT_MAX_FEE_PER_GAS_GWEI,
)
@click.option(
    '--hot-wallet-password-file',
    type=click.Path(exists=True, file_okay=True, dir_okay=False),
    envvar='HOT_WALLET_PASSWORD_FILE',
    help='Absolute path to the hot wallet password file. '
    'Default is the file generated with "create-wallet" command.',
)
@click.option(
    '--hot-wallet-file',
    type=click.Path(exists=True, file_okay=True, dir_okay=False),
    envvar='HOT_WALLET_FILE',
    help='Absolute path to the hot wallet. '
    'Default is the file generated with "create-wallet" command.',
)
@click.option(
    '--no-keystores',
    is_flag=True,
    envvar='NO_KEYSTORES',
    help='If this option is enabled then exit signatures are generated by another service. '
    'Disabled by default.',
)
@click.option(
    '--keystores-password-file',
    type=click.Path(exists=True, file_okay=True, dir_okay=False),
    envvar='KEYSTORES_PASSWORD_FILE',
    help='Absolute path to the password file for decrypting keystores. '
    'Default is the file generated with "create-keys" command.',
)
@click.option(
    '--keystores-dir',
    type=click.Path(exists=True, file_okay=False, dir_okay=True),
    envvar='KEYSTORES_DIR',
    help='Absolute path to the directory with all the encrypted keystores. '
    'Default is the directory generated with "create-keys" command.',
)
@click.option(
    '--deposit-data-file',
    type=click.Path(exists=True, file_okay=True, dir_okay=False),
    envvar='DEPOSIT_DATA_FILE',
    help='Path to the deposit_data.json file. '
    'Default is the file generated with "create-keys" command.',
)
@click.option(
    '--network',
    type=click.Choice(
        AVAILABLE_NETWORKS,
        case_sensitive=False,
    ),
    envvar='NETWORK',
    help='The network of the vault. Default is the network specified at "init" command.',
)
@click.option(
    '--enable-metrics',
    is_flag=True,
    envvar='ENABLE_METRICS',
    help='Whether to enable metrics server. Disabled by default.',
)
@click.option(
    '--metrics-host',
    type=str,
    help=f'The prometheus metrics host. Default is {DEFAULT_METRICS_HOST}.',
    envvar='METRICS_HOST',
    default=DEFAULT_METRICS_HOST,
)
@click.option(
    '--metrics-port',
    type=int,
    help=f'The prometheus metrics port. Default is {DEFAULT_METRICS_PORT}.',
    envvar='METRICS_PORT',
    default=DEFAULT_METRICS_PORT,
)
@click.option(
    '-v',
    '--verbose',
    help='Enable debug mode. Default is false.',
    envvar='VERBOSE',
    is_flag=True,
)
@click.option(
    '--harvest-vault',
    is_flag=True,
    envvar='HARVEST_VAULT',
    help='Whether to submit vault harvest transactions. Default is false.',
)
@click.option(
    '--execution-endpoints',
    type=str,
    envvar='EXECUTION_ENDPOINTS',
    prompt='Enter comma separated list of API endpoints for execution nodes',
    help='Comma separated list of API endpoints for execution nodes.',
)
@click.option(
    '--consensus-endpoints',
    type=str,
    envvar='CONSENSUS_ENDPOINTS',
    prompt='Enter comma separated list of API endpoints for consensus nodes',
    help='Comma separated list of API endpoints for consensus nodes.',
)
@click.option(
    '--vault',
    type=ChecksumAddress,
    callback=validate_eth_address,
    envvar='VAULT',
    prompt='Enter the vault address',
    help='Address of the vault to register validators for.',
)
@click.option(
    '--remote-signer-url',
    type=str,
    envvar='REMOTE_SIGNER_URL',
    help='The base URL of the remote signer, e.g. http://signer:9000',
)
@click.option(
    '--hashi-vault-url',
    envvar='HASHI_VAULT_URL',
    help='The base URL of the vault service, e.g. http://vault:8200.',
)
@click.option(
    '--hashi-vault-token',
    envvar='HASHI_VAULT_TOKEN',
    help='Authentication token for accessing Hashi vault.',
)
@click.option(
    '--hashi-vault-key-path',
    envvar='HASHI_VAULT_KEY_PATH',
    help='Key path in the K/V secret engine where validator signing keys are stored.',
)
@click.option(
    '--log-format',
    type=click.Choice(
        LOG_FORMATS,
        case_sensitive=False,
    ),
    default=LOG_PLAIN,
    envvar='LOG_FORMAT',
    help='The log record format. Can be "plain" or "json".',
)
@click.option(
    '--log-level',
    type=click.Choice(
        [
            'FATAL',
            'ERROR',
            'WARNING',
            'INFO',
            'DEBUG',
        ],
        case_sensitive=False,
    ),
    default='INFO',
    envvar='LOG_LEVEL',
    help='The log level.',
)
@click.option(
    '--enable-api',
    is_flag=True,
    envvar='ENABLE_API',
    help='Whether to enable API server. Disabled by default.',
)
@click.option(
    '--api-host',
    type=str,
    help=f'API host. Default is {DEFAULT_API_HOST}.',
    envvar='API_HOST',
    default=DEFAULT_API_HOST,
)
@click.option(
    '--api-port',
    type=int,
    help=f'API port. Default is {DEFAULT_API_PORT}.',
    envvar='API_PORT',
    default=DEFAULT_API_PORT,
)
@click.option(
    '--validators-registration-mode',
    type=click.Choice(['AUTO', 'API'], case_sensitive=False),
    default='AUTO',
    envvar='VALIDATORS_REGISTRATION_MODE',
    help='AUTO mode: validators are registered automatically when vault assets are enough.\n'
    'API mode: validators registration is triggered by API request.',
)
@click.command(help='Start operator service')
# pylint: disable-next=too-many-arguments,too-many-locals
def start(
    vault: ChecksumAddress,
    consensus_endpoints: str,
    execution_endpoints: str,
    harvest_vault: bool,
    verbose: bool,
    enable_metrics: bool,
    metrics_host: str,
    metrics_port: int,
    data_dir: str,
    log_level: str,
    log_format: str,
    network: str | None,
    deposit_data_file: str | None,
    no_keystores: bool,
    keystores_dir: str | None,
    keystores_password_file: str | None,
    remote_signer_url: str | None,
    hashi_vault_key_path: str | None,
    hashi_vault_token: str | None,
    hashi_vault_url: str | None,
    hot_wallet_file: str | None,
    hot_wallet_password_file: str | None,
    max_fee_per_gas_gwei: int,
    database_dir: str | None,
    enable_api: bool,
    api_host: str,
    api_port: int,
    validators_registration_mode: str,
) -> None:
    vault_config = VaultConfig(vault, Path(data_dir))
    if network is None:
        vault_config.load()
        network = vault_config.network

    settings.set(
        vault=vault,
        vault_dir=vault_config.vault_dir,
        consensus_endpoints=consensus_endpoints,
        execution_endpoints=execution_endpoints,
        harvest_vault=harvest_vault,
        verbose=verbose,
        enable_metrics=enable_metrics,
        metrics_host=metrics_host,
        metrics_port=metrics_port,
        network=network,
        deposit_data_file=deposit_data_file,
        no_keystores=no_keystores,
        keystores_dir=keystores_dir,
        keystores_password_file=keystores_password_file,
        remote_signer_url=remote_signer_url,
        hashi_vault_token=hashi_vault_token,
        hashi_vault_key_path=hashi_vault_key_path,
        hashi_vault_url=hashi_vault_url,
        hot_wallet_file=hot_wallet_file,
        hot_wallet_password_file=hot_wallet_password_file,
        max_fee_per_gas_gwei=max_fee_per_gas_gwei,
        database_dir=database_dir,
        log_level=log_level,
        log_format=log_format,
        enable_api=enable_api,
        api_host=api_host,
        api_port=api_port,
        validators_registration_mode=ValidatorsRegistrationMode[validators_registration_mode],
    )

    try:
        asyncio.run(main())
    except Exception as e:
        log_verbose(e)


async def main() -> None:
    setup_logging()
    setup_sentry()
    log_start()

    if not settings.skip_startup_checks:
        await startup_checks()

    NetworkValidatorCrud().setup()

    # load network validators from ipfs dump
    await load_genesis_validators()

    # load keystore
    keystore = await load_keystore()

    # load deposit data
    deposit_data = load_deposit_data(settings.vault, settings.deposit_data_file)
    logger.info('Loaded deposit data file %s', settings.deposit_data_file)
    # start operator tasks

    # periodically scan network validator updates
    network_validators_processor = NetworkValidatorsProcessor()
    network_validators_scanner = EventScanner(network_validators_processor)

    logger.info('Syncing network validator events...')
    chain_state = await get_chain_finalized_head()
    await network_validators_scanner.process_new_events(chain_state.execution_block)

    logger.info('Warming up oracles cache...')
    await get_oracles()

    if settings.enable_api:
        logger.info('Starting api server')
        api_app.state.deposit_data = deposit_data

        config = uvicorn.Config(
            api_app,
            host=settings.api_host,
            port=settings.api_port,
            log_config=None,
        )
        server = UvicornServerWithoutSignals(config)
        asyncio.create_task(server.serve())

    if settings.enable_metrics:
        await metrics_server()

    logger.info('Started operator service')
    with InterruptHandler() as interrupt_handler:
        tasks = [
            ValidatorsTask(
                keystore=keystore,
                deposit_data=deposit_data,
            ).run(interrupt_handler),
            ExitSignatureTask(
                keystore=keystore,
            ).run(interrupt_handler),
            MetricsTask().run(interrupt_handler),
            WalletTask().run(interrupt_handler),
        ]
        if settings.harvest_vault:
            tasks.append(HarvestTask().run(interrupt_handler))

        await asyncio.gather(*tasks)


class UvicornServerWithoutSignals(uvicorn.Server):
    def install_signal_handlers(self) -> None:
        # Manage signals in command, not in Uvicorn
        pass


def log_start() -> None:
    build = get_build_version()
    start_str = 'Starting operator service'

    if build:
        logger.info('%s, version %s, build %s', start_str, src.__version__, build)
    else:
        logger.info('%s, version %s', start_str, src.__version__)


def setup_sentry():
    if settings.sentry_dsn:
        # pylint: disable-next=import-outside-toplevel
        import sentry_sdk

        sentry_sdk.init(settings.sentry_dsn, traces_sample_rate=0.1)
        sentry_sdk.set_tag('network', settings.network)
        sentry_sdk.set_tag('vault', settings.vault)


def setup_logging():
    if settings.log_format == LOG_JSON:
        formatter = JsonFormatter('%(timestamp)s %(level)s %(name)s %(message)s')
        logHandler = logging.StreamHandler()
        logHandler.setFormatter(formatter)
        logging.basicConfig(
            level=settings.log_level,
            handlers=[logHandler],
        )
    else:
        logging.basicConfig(
            format='%(asctime)s %(levelname)-8s %(message)s',
            datefmt=LOG_DATE_FORMAT,
            level=settings.log_level,
        )
    if not settings.verbose:
        logging.getLogger('sw_utils.execution').setLevel(logging.ERROR)
        logging.getLogger('sw_utils.consensus').setLevel(logging.ERROR)
        logging.getLogger('sw_utils.ipfs').setLevel(logging.ERROR)
        logging.getLogger('sw_utils.decorators').setLevel(logging.ERROR)

        # Logging config does not affect messages issued by `warnings` module
        warnings.simplefilter('ignore')
